CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "mlcppapp_test"."org_status" AS ENUM (
  'active',
  'paused',
  'cancelled'
);

CREATE TYPE "mlcppapp_test"."client_status" AS ENUM (
  'pending',
  'cancelled',
  'active',
  'archived'
);


CREATE TYPE "mlcppapp_test"."agent_status" AS ENUM (
  'active',
  'archived'
);

CREATE TYPE "mlcppapp_test"."clientterm_status" AS ENUM (
  'active',
  'expired'
);


CREATE TABLE "mlcppapp_test"."system" (
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "up" boolean
);

-- The organisation
CREATE TABLE "mlcppapp_test"."organisation" (
    "id" uuid DEFAULT uuid_generate_v4 (),
    "serviceId" varchar,
    "name" varchar(256),
    "status" mlcppapp_test.org_status,
    "key" varchar(16),
    "websiteUrl" varchar(1024),
    "primaryDomain" varchar(256) unique,
    "logoThumbnail" text,
    "signupKey" text,
    "bffRegistered" boolean,
    "welcomeMessageTemplate" text,
    PRIMARY KEY (id)
);

-- Roles for the organisation
CREATE TABLE "mlcppapp_test"."role" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orgId" uuid not null,
    "name" varchar(256),
    "created" timestamp,
    "lastModified" timestamp
);
ALTER TABLE "mlcppapp_test"."role" ADD FOREIGN KEY ("orgId") REFERENCES "mlcppapp_test"."organisation" ("id");


-- Agents (users) for the organisation
CREATE TABLE "mlcppapp_test"."agent" (
    "id" uuid DEFAULT uuid_generate_v4 (),
    "roleId" bigint not null,
    "orgId" uuid not null,
    "name" varchar(256),
    "email" varchar(1024) unique,
    "phone" varchar(10),
    "status" mlcppapp_test.agent_status,
    "photo" text,
    "created" timestamp,
    "lastModified" timestamp,
    PRIMARY KEY (id)
);
ALTER TABLE "mlcppapp_test"."agent" ADD FOREIGN KEY ("orgId") REFERENCES "mlcppapp_test"."organisation" ("id");
ALTER TABLE "mlcppapp_test"."agent" ADD FOREIGN KEY ("roleId") REFERENCES "mlcppapp_test"."role" ("id");


CREATE TABLE "mlcppapp_test"."client" (
    "id" uuid DEFAULT uuid_generate_v4 (),
    "orgId" uuid,
    "serviceId" varchar,
    "vaultId" varchar,
    "name" varchar(256),
    "email" varchar(1024) unique,
    "status" mlcppapp_test.client_status,
    "phone" varchar(10),
    "ref" text,
    "notes" text,
    "created" timestamp,
    "lastModified" timestamp,
    "invitationId" varchar(256),
    "meecoConnectionId" varchar(256),
    "meecoUserId" varchar(256),
    PRIMARY KEY (id)
);
ALTER TABLE "mlcppapp_test"."client" ADD FOREIGN KEY ("orgId") REFERENCES "mlcppapp_test"."organisation" ("id");
ALTER TABLE "mlcppapp_test"."client" ADD CONSTRAINT "meccoUser_org_un" UNIQUE ("orgId", "meecoUserId");
ALTER TABLE "mlcppapp_test"."client" ADD CONSTRAINT "meecoConnection_org_un" UNIQUE ("orgId", "meecoConnectionId");

CREATE TABLE "mlcppapp_test"."clientterm" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" uuid,
    "start" timestamp,
    "end" timestamp,
    "durationMonths" int,
    "status" mlcppapp_test.clientterm_status,
    "createdBy" varchar,
    "created" timestamp
);
ALTER TABLE "mlcppapp_test"."clientterm" ADD FOREIGN KEY ("clientId") REFERENCES "mlcppapp_test"."client" ("id");


CREATE TABLE "mlcppapp_test"."agentclient" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "agentId" uuid,
    "clientId" uuid,
    "created" timestamp,
    "lastModified" timestamp
);
ALTER TABLE "mlcppapp_test"."agentclient" ADD FOREIGN KEY ("agentId") REFERENCES "mlcppapp_test"."agent" ("id");
ALTER TABLE "mlcppapp_test"."agentclient" ADD FOREIGN KEY ("clientId") REFERENCES "mlcppapp_test"."client" ("id");


CREATE TABLE "mlcppapp_test"."audit" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orgId" uuid,
    "agentId" uuid,
    "clientId" uuid,
    "action" varchar(64),
    "details" text,
    "time" timestamp
);


CREATE TABLE "mlcppapp_test"."activities" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "agentId" uuid,
    "clientId" uuid,
    "title" varchar,
    "name" varchar,
    "message" varchar,
    "section" varchar,
    "read" boolean,
    "created" timestamp
);
ALTER TABLE "mlcppapp_test"."activities" ADD FOREIGN KEY ("agentId") REFERENCES "mlcppapp_test"."agent" ("id");
ALTER TABLE "mlcppapp_test"."activities" ADD FOREIGN KEY ("clientId") REFERENCES "mlcppapp_test"."client" ("id");

CREATE TABLE "mlcppapp_test"."unreadmessages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "messageId" varchar,
    "orgId" uuid,
    "agentId" uuid,
    "clientId" uuid
);
ALTER TABLE "mlcppapp_test"."unreadmessages" ADD FOREIGN KEY ("orgId") REFERENCES "mlcppapp_test"."organisation" ("id");
ALTER TABLE "mlcppapp_test"."unreadmessages" ADD FOREIGN KEY ("agentId") REFERENCES "mlcppapp_test"."agent" ("id");
ALTER TABLE "mlcppapp_test"."unreadmessages" ADD FOREIGN KEY ("clientId") REFERENCES "mlcppapp_test"."client" ("id");