version: '3.8'

services:
  postgres1:
    image: postgres:latest
    container_name: postgres1
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    networks:
      - psql_network

  postgres2:
    image: postgres:latest
    container_name: postgres2
    restart: always
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    networks:
      - psql_network

  pgadmin1:
    image: dpage/pgadmin4:latest
    container_name: pgadmin1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1
    ports:
      - "8081:80"
    networks:
      - psql_network

  pgadmin2:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin2@example.com
      PGADMIN_DEFAULT_PASSWORD: admin2
    ports:
      - "8082:80"
    networks:
      - psql_network

networks:
  psql_network: